### ISSUE TITLE
ld: library not found for -lMSColorPicker

### ISSUE THREAD

**Issue by pmcgreevy3103** [sgl0v/MSColorPicker#10]
Hi
I see that this has been reported before and resolved, but when attempting to compile the Demo project I get the following linker issue;

ld: warning: directory not found for option '-L/Users/Paul/Library/Developer/Xcode/DerivedData/MSColorPickerDemo-aepbaxofjcjllwdxkjhethtpzksr/Build/Products/Debug-iphonesimulator/MSColorPicker'
ld: library not found for -lMSColorPicker
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And suggestions on how to resolve?  Thanks.

Paul

**Comment by sgl0v** [comment]
Hi, 

You have to run `pod install` from the MSColorPickerDemo dir. Just re-open and build the project after that.

Best regards,
Max
