### ISSUE TITLE
3 errors

### ISSUE THREAD

**Issue by IosForZhang** [sgl0v/MSColorPicker#3]
diff: /../Podfile.lock: No such file or directory

diff: /Manifest.lock: No such file or directory

error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by sgl0v** [comment]
Just run the next from the terminal:

```
pod install
```

If you don't have cocoapods installed, first run

```
sudo gem install cocoapods
```
